In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "/Users/karollvivianalopezvillegas/GitHub/OKVET_DA_Final_project/04_Datasets_final/df_OKVET_Fórmulas_médicas.xlsx"

In [3]:
df = pd.read_excel(url)

In [4]:
df.drop( columns = ["Medicamentos 2"] , inplace = True)

In [5]:
df.head(1)

,Fecha fórmula,Diagnóstico presuntivo y/o final,Medicamentos 1,Paciente,Especie,Raza,Género,E.Reproductivo,Fecha nacimiento,Edad,Cliente,Identificación,Autor,Fecha registro,Fecha edición
0,2024-01-19,laceracion,Nombre: clorhexidinaPresentación: sprayCantida...,piña,Felino,Criollo(a),Hembra,Esterilizado,2021-01-15,"3 años, 6 meses y 18 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 17:59:05,2024-01-19 17:59:05

In [6]:
patron = 'Nombre: (.*?)Presentación'
nombres_medicamentos = df['Medicamentos 1'].str.extractall(patron)

In [7]:
nombres_medicamentos

                                                         0
    match
0   0                                         clorhexidina
    1                                       acido fusidico
1   0                                             cosequin
    1                                           natur proc
    2                                             engystol
...                                                    ...
622 0      Antax suspensión de caléndula (farmacia humana)
    1                                            Canisan D
    2                                  Metronid suspensión
    3                                    Fortiflora sobres
    4                                Cambio de concentrado

[1990 rows x 1 columns]

In [8]:
nombres_medicamentos.reset_index(inplace=True)

In [9]:
nombres_medicamentos

      level_0  match                                                0
0           0      0                                     clorhexidina
1           0      1                                   acido fusidico
2           1      0                                         cosequin
3           1      1                                       natur proc
4           1      2                                         engystol
...       ...    ...                                              ...
1985      622      0  Antax suspensión de caléndula (farmacia humana)
1986      622      1                                        Canisan D
1987      622      2                              Metronid suspensión
1988      622      3                                Fortiflora sobres
1989      622      4                            Cambio de concentrado

[1990 rows x 3 columns]

In [10]:
nombres_medicamentos.columns = ['indice_original', 'medicamento_num', 'nombre_medicamento']

In [11]:
nombres_medicamentos

,indice_original,medicamento_num,nombre_medicamento
0,0,0,clorhexidina
1,0,1,acido fusidico
2,1,0,cosequin
3,1,1,natur proc
4,1,2,engystol
...,...,...,...
1985,622,0,Antax suspensión de caléndula (farmacia humana)
1986,622,1,Canisan D
1987,622,2,Metronid suspensión
1988,622,3,Fortiflora sobres
1989,622,4,Cambio de concentrado

In [12]:
nombres_medicamentos['medicamento_num'] += 1

In [13]:
nombres_medicamentos

,indice_original,medicamento_num,nombre_medicamento
0,0,1,clorhexidina
1,0,2,acido fusidico
2,1,1,cosequin
3,1,2,natur proc
4,1,3,engystol
...,...,...,...
1985,622,1,Antax suspensión de caléndula (farmacia humana)
1986,622,2,Canisan D
1987,622,3,Metronid suspensión
1988,622,4,Fortiflora sobres
1989,622,5,Cambio de concentrado

In [14]:
# Aseguramos que 'indice_original' es del mismo tipo en ambos DataFrames para el merge
df.reset_index(inplace=True)
nombres_medicamentos['indice_original'] = nombres_medicamentos['indice_original'].astype(df.index.dtype)

In [18]:
df.head(3)

,index,Fecha fórmula,Diagnóstico presuntivo y/o final,Medicamentos 1,Paciente,Especie,Raza,Género,E.Reproductivo,Fecha nacimiento,Edad,Cliente,Identificación,Autor,Fecha registro,Fecha edición
0,0,2024-01-19,laceracion,Nombre: clorhexidinaPresentación: sprayCantida...,piña,Felino,Criollo(a),Hembra,Esterilizado,2021-01-15,"3 años, 6 meses y 18 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 17:59:05,2024-01-19 17:59:05
1,1,2024-01-19,artritis? enfermedad periodontal,Nombre: cosequinPresentación: gomasCantidad: 1...,rapunzel,Felino,Criollo(a),Hembra,Esterilizado,2014-06-18,"10 años, 1 meses y 15 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 18:07:28,2024-01-19 18:07:28
2,2,2024-03-15,Periodontitis localizada,Nombre: Pregabalina 20 mg/mlPresentación: Susp...,rapunzel,Felino,Criollo(a),Hembra,Esterilizado,2014-06-18,"10 años, 1 meses y 15 días",Adriana Acebedo,42897589,Isabella Quiroga,2024-03-15 09:50:54,2024-03-15 09:58:43

In [19]:
nombres_medicamentos.head(3)

   indice_original  medicamento_num nombre_medicamento
0                0                1       clorhexidina
1                0                2     acido fusidico
2                1                1           cosequin

In [20]:
# Hacemos un merge entre el DataFrame original y los medicamentos extraídos
df_final = pd.merge(df, nombres_medicamentos, left_on='index', right_on='indice_original')

In [21]:
df_final.head(3)

,index,Fecha fórmula,Diagnóstico presuntivo y/o final,Medicamentos 1,Paciente,Especie,Raza,Género,E.Reproductivo,Fecha nacimiento,Edad,Cliente,Identificación,Autor,Fecha registro,Fecha edición,indice_original,medicamento_num,nombre_medicamento
0,0,2024-01-19,laceracion,Nombre: clorhexidinaPresentación: sprayCantida...,piña,Felino,Criollo(a),Hembra,Esterilizado,2021-01-15,"3 años, 6 meses y 18 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 17:59:05,2024-01-19 17:59:05,0,1,clorhexidina
1,0,2024-01-19,laceracion,Nombre: clorhexidinaPresentación: sprayCantida...,piña,Felino,Criollo(a),Hembra,Esterilizado,2021-01-15,"3 años, 6 meses y 18 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 17:59:05,2024-01-19 17:59:05,0,2,acido fusidico
2,1,2024-01-19,artritis? enfermedad periodontal,Nombre: cosequinPresentación: gomasCantidad: 1...,rapunzel,Felino,Criollo(a),Hembra,Esterilizado,2014-06-18,"10 años, 1 meses y 15 días",Adriana Acebedo,42897589,Paula Andrea Bernal Yepes,2024-01-19 18:07:28,2024-01-19 18:07:28,1,1,cosequin

In [22]:
df_final.columns

Index(['index', 'Fecha fórmula', 'Diagnóstico presuntivo y/o final',
       'Medicamentos 1', 'Paciente', 'Especie', 'Raza', 'Género',
       'E.Reproductivo', 'Fecha nacimiento', 'Edad', 'Cliente',
       'Identificación', 'Autor', 'Fecha registro', 'Fecha edición',
       'indice_original', 'medicamento_num', 'nombre_medicamento'],
      dtype='object')

In [25]:
df_final = df_final[['medicamento_num', 'nombre_medicamento', 'Paciente', 'Cliente', 'Especie', 'Raza', 'Género', 'E.Reproductivo',  'Identificación',  'Fecha fórmula','Fecha registro', 'Fecha edición','Autor', 'Medicamentos 1','Fecha nacimiento', 'Edad', 'Diagnóstico presuntivo y/o final', 'index','indice_original']]

In [27]:
df_final.head(3)

,medicamento_num,nombre_medicamento,Paciente,Cliente,Especie,Raza,Género,E.Reproductivo,Identificación,Fecha fórmula,Fecha registro,Fecha edición,Autor,Medicamentos 1,Fecha nacimiento,Edad,Diagnóstico presuntivo y/o final,index,indice_original
0,1,clorhexidina,piña,Adriana Acebedo,Felino,Criollo(a),Hembra,Esterilizado,42897589,2024-01-19,2024-01-19 17:59:05,2024-01-19 17:59:05,Paula Andrea Bernal Yepes,Nombre: clorhexidinaPresentación: sprayCantida...,2021-01-15,"3 años, 6 meses y 18 días",laceracion,0,0
1,2,acido fusidico,piña,Adriana Acebedo,Felino,Criollo(a),Hembra,Esterilizado,42897589,2024-01-19,2024-01-19 17:59:05,2024-01-19 17:59:05,Paula Andrea Bernal Yepes,Nombre: clorhexidinaPresentación: sprayCantida...,2021-01-15,"3 años, 6 meses y 18 días",laceracion,0,0
2,1,cosequin,rapunzel,Adriana Acebedo,Felino,Criollo(a),Hembra,Esterilizado,42897589,2024-01-19,2024-01-19 18:07:28,2024-01-19 18:07:28,Paula Andrea Bernal Yepes,Nombre: cosequinPresentación: gomasCantidad: 1...,2014-06-18,"10 años, 1 meses y 15 días",artritis? enfermedad periodontal,1,1

In [29]:
#df_final.to_excel("/Users/karollvivianalopezvillegas/GitHub/OKVET_DA_Final_project/04_Datasets_final/df_OKVET_Fórmulas_split.xlsx", index = False)