In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "/Users/karollvivianalopezvillegas/GitHub/OKVET_DA_Final_project/02_Datasets_pre_cleaning/TuFórmula_Compras.xlsx"

In [3]:
df = pd.read_excel(url)

In [4]:
df.shape

(171, 10)

In [5]:
df.head() # ACCIONES: Columnas a eliminar: Factura ; convetir "CANTIDAD" y "UNIDAD"" a Integer

,PRODUCTO,FECHA COMPRA,PROVEEDOR,FACTURA,CANTIDAD,COSTO,IVA,COSTO TOTAL,UNIDAD,COSTO UNIDAD
0,Cardial B 5ml (comprimidos),2024-02-06,Gabrica S.A.S.,MED325011,3.0,93480.0,0.0,280440.0,3.0,93480.00
1,Lata I/D Hill's pollo y vegetales 12.5 OZ,2024-02-06,Gabrica S.A.S.,MED325011,1.0,57855.0,0.0,57855.0,4.0,14463.75
2,Cosequin 60 felino (gominolas),2024-02-07,Andrés Cosequin,0000099600,1.0,99000.0,0.0,99000.0,1.0,99000.00
3,Acar clean 400ml (spray),2024-02-10,Almacenes Éxito S.A.S.,GA011002560,1.0,38200.0,0.0,38200.0,1.0,38200.00
4,Cefalexina 500mg (tabletas),2024-02-10,Droguería Específica S.A.S.,796325,1.0,56000.0,0.0,56000.0,10.0,5600.00

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171 entries, 0 to 170
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PRODUCTO      171 non-null    object
 1   FECHA COMPRA  171 non-null    datetime64[ns]
 2   PROVEEDOR     171 non-null    object
 3   FACTURA       163 non-null    object
 4   CANTIDAD      170 non-null    float64
 5   COSTO         170 non-null    float64
 6   IVA           170 non-null    float64
 7   COSTO TOTAL   170 non-null    float64
 8   UNIDAD        170 non-null    float64
 9   COSTO UNIDAD  170 non-null    float64
dtypes: datetime64[ns](1), float64(6), object(3)
memory usage: 13.5+ KB

In [7]:
df.isna().sum()

PRODUCTO        0
FECHA COMPRA    0
PROVEEDOR       0
FACTURA         8
CANTIDAD        1
COSTO           1
IVA             1
COSTO TOTAL     1
UNIDAD          1
COSTO UNIDAD    1
dtype: int64

In [8]:
df.nunique()

PRODUCTO        109
FECHA COMPRA     56
PROVEEDOR        23
FACTURA          88
CANTIDAD          5
COSTO           123
IVA               7
COSTO TOTAL     134
UNIDAD           14
COSTO UNIDAD    133
dtype: int64

In [10]:
df.drop(columns = "FACTURA", inplace = True)

In [11]:
df.head()

,PRODUCTO,FECHA COMPRA,PROVEEDOR,CANTIDAD,COSTO,IVA,COSTO TOTAL,UNIDAD,COSTO UNIDAD
0,Cardial B 5ml (comprimidos),2024-02-06,Gabrica S.A.S.,3.0,93480.0,0.0,280440.0,3.0,93480.00
1,Lata I/D Hill's pollo y vegetales 12.5 OZ,2024-02-06,Gabrica S.A.S.,1.0,57855.0,0.0,57855.0,4.0,14463.75
2,Cosequin 60 felino (gominolas),2024-02-07,Andrés Cosequin,1.0,99000.0,0.0,99000.0,1.0,99000.00
3,Acar clean 400ml (spray),2024-02-10,Almacenes Éxito S.A.S.,1.0,38200.0,0.0,38200.0,1.0,38200.00
4,Cefalexina 500mg (tabletas),2024-02-10,Droguería Específica S.A.S.,1.0,56000.0,0.0,56000.0,10.0,5600.00

In [12]:
df.dropna(subset = ["CANTIDAD", "UNIDAD"], inplace = True)

In [13]:
df

,PRODUCTO,FECHA COMPRA,PROVEEDOR,CANTIDAD,COSTO,IVA,COSTO TOTAL,UNIDAD,COSTO UNIDAD
0,Cardial B 5ml (comprimidos),2024-02-06,Gabrica S.A.S.,3.0,93480.0,0.0,280440.0,3.0,93480.00
1,Lata I/D Hill's pollo y vegetales 12.5 OZ,2024-02-06,Gabrica S.A.S.,1.0,57855.0,0.0,57855.0,4.0,14463.75
2,Cosequin 60 felino (gominolas),2024-02-07,Andrés Cosequin,1.0,99000.0,0.0,99000.0,1.0,99000.00
3,Acar clean 400ml (spray),2024-02-10,Almacenes Éxito S.A.S.,1.0,38200.0,0.0,38200.0,1.0,38200.00
4,Cefalexina 500mg (tabletas),2024-02-10,Droguería Específica S.A.S.,1.0,56000.0,0.0,56000.0,10.0,5600.00
...,...,...,...,...,...,...,...,...,...
166,"Nexgard Spectra 7,5 a 15kg (38/bmg) (tableta)",2024-06-26,Ivanagro - Inversiones El Rebaño S.A.S.,1.0,43250.0,0.0,43250.0,1.0,43250.00
167,Fórmula Magistral,2024-06-27,Fórmula Animal - Emcomag S.A.S.,1.0,42755.0,0.0,42755.0,1.0,42755.00
168,"Thyro tabs 0,2mg 120tab (tabletas)",2024-06-27,Finca Urbana Pets S.A.S.,1.0,46100.0,0.0,46100.0,1.0,46100.00
169,Amoxicilina + acido clavulanico (nicilan) 500 mg,2024-06-29,Dropopular S.A.S.,1.0,86800.0,0.0,86800.0,14.0,6200.00
170,Previcox 227mg (comprimidos),2024-06-29,Finca Urbana Pets S.A.S.,5.0,7400.0,0.0,37000.0,5.0,7400.00

In [14]:
df["UNIDAD"] = df["UNIDAD"].astype(int)

In [15]:
df["CANTIDAD"] = df["CANTIDAD"].astype(int)

In [16]:
df.dtypes

PRODUCTO                object
FECHA COMPRA    datetime64[ns]
PROVEEDOR               object
CANTIDAD                 int64
COSTO                  float64
IVA                    float64
COSTO TOTAL            float64
UNIDAD                   int64
COSTO UNIDAD           float64
dtype: object

In [17]:
# df.to_excel("/Users/karollvivianalopezvillegas/GitHub/OKVET_DA_Final_project/04_Datasets_final/df_TuFórmula_Compras.xlsx", index = False)